[project]
# Whether to enable telemetry (default: true)
enable_telemetry = false

# List of environment variables to be provided by each user to use the app
user_env = []

# Duration (in seconds) during which the session is kept alive after the last user message
session_timeout = 3600

# Enable third party tracking (Posthog)
enable_third_party_tracking = false

# Follow symlink for project files
follow_symlinks = false

[UI]
# Name of the app and chatbot
name = "Tohecho"

# Description of the app and chatbot
description = "Your personal assistant to help you get your project work done faster"

# The default value for the expand messages settings (default: false)
default_expand_messages = false

# Hide the chain of thought details from the user (default: false)
hide_cot = false

[features]
# Show the prompt playground (default: true)
prompt_playground = true

