services:
  neo4j:
    image: neo4j:5
    ports:
      - "7474:7474"   # Web browser
      - "7687:7687"   # Bolt
    environment:
      - NEO4J_AUTH=neo4j/test1234
    volumes:
      - neo4j_data:/data

  mcp:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    ports:
      - "8002:8002"
    command:
      [
        "--transport", "sse",
        "--port", "8002",
        "--jira-url", "${JIRA_INSTANCE_URL}",
        "--jira-username", "${JIRA_USERNAME}",
        "--jira-token", "${JIRA_API_TOKEN}"
      ]
    environment:
      - JIRA_INSTANCE_URL=${JIRA_INSTANCE_URL}
      - JIRA_USERNAME=${JIRA_USERNAME}
      - JIRA_API_TOKEN=${JIRA_API_TOKEN}

  chainlit-app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - neo4j
      - mcp

volumes:
  neo4j_data:
