name: Enable GitHub Pages

on:
  workflow_dispatch: # Manual trigger only

permissions:
  pages: write
  id-token: write

jobs:
  enable-pages:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Create initial page
      run: |
        mkdir -p docs
        echo "# Tahecho - BSI TR-03183 Compliance" > docs/index.md
        echo "" >> docs/index.md
        echo "SBOM reports and compliance documentation will be published here automatically." >> docs/index.md
        
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4 